### ISSUE TITLE
hab pkg export docker giving error

### ISSUE THREAD

**Issue by siva517** [trickyearlobe/hab_nexus#1] opened 2019-09-25 20:42 UTC
Hello,

Thank you for developing the habitat package for Nexus.

Everthing looks good but when I try to export it as a docker images, its failing with "`nexus.vmoptions' was not found under any 'PATH' directories in the sthumati/nexus/3.15.2/20190925203439 package"  

Any configuration that I should provide to access the nexus.vmoptions file? 

Thank you for your time on this.

**Comment by siva517** [comment] 2019-09-25 20:42
Command I used to run is 'hab pkg export docker sthumati-nexus-3.15.2-20190925203439-x86_64-linux.hart'

**Comment by trickyearlobe** [comment] 2022-09-22 13:18
Hey sorry @siva517,
I didn't notice this issue pop up (normally I get a notification, but I just realised I don't have a watch on this repo).

I'll take a look at why this occurs.

**Comment by trickyearlobe** [comment] 2022-09-22 16:14
Looks like the issue is caused by a dangling symlink that I used at build time to avoid a problem where services that run as the `hab` user don't have permissions to create symlinks at run time. Docker doesn't like them.

Fixing this will require hard coding the path to the sonatype work dir to `/hab/svc/nexus/data/sonatype-work` instead of letting it be a hab config option. I doubt this will impact anyone as its easy to mount directories or symlinks into that location for docker or standard VM deployments.

**Comment by trickyearlobe** [comment] 2022-09-22 17:08
Should be fixed by https://github.com/trickyearlobe/hab_nexus/commit/cd88819c57fae4d60b14989054bd10b2a68c3fc8

**Comment by trickyearlobe** [comment] 2022-10-01 04:10
Hi @siva517,
Closing this issue as fixed... let me know if you run into other problems, and sorry it took me so long to see the open issue.

**Closed as completed by trickyearlobe** 2022-10-01 04:10 UTC
Labels: bug
